FROM node:alpine

RUN yarn global add \
    vuepress \
    @vuepress/plugin-pwa \
    @vuepress/plugin-back-to-top

RUN mkdir -p /vuepress/docs

COPY scripts/dev.sh /dev.sh
RUN chmod +x /dev.sh
EXPOSE 8080
ENTRYPOINT ["sh", "/dev.sh"]